In [13]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [14]:
# filePath = "/mnt/raid/home/ayrisbud/us-famli-pl/src/new_annotated_data.csv"
# myDf = pd.read_csv("/mnt/raid/home/ayrisbud/us-famli-pl/src/new_annotated_data.csv")
dfTrain = pd.read_csv("/mnt/raid/home/ayrisbud/us-famli-pl/src/annotatedTrain.csv")
dfTest = pd.read_csv("/mnt/raid/home/ayrisbud/us-famli-pl/src/annotatedTest.csv")
dfVal =pd.read_csv("/mnt/raid/home/ayrisbud/us-famli-pl/src/annotatedVal.csv")

In [15]:
print(dfTest.columns)

Index(['img_path', 'uuid', 'study_id', 'fetal_presentation_str', 'ga_boe',
       'ga_expert', 'famli_edd_source', 'famli_edd_source_detail', 'dvp_crf',
       'fetal_presentation', 'ga_absdiff', 'is_anchor', 'tag', 'pidscan',
       'us_plac', 'us_previa', 'placenta_str', 'previa_str', 'Manufacturer',
       'ManufacturerModelName', 'uuid_path_256', 'score', 'pred',
       'pred_cluster', 'File', 'No structures visible', 'Head Visible',
       'Abdomen Visible', 'Chest Visible', 'Femur Visible',
       'Other arm or leg bones visible', 'Umbilical cord visible',
       'Amniotic fluid visible', 'Placenta visible', 'Fetus or CRL visible',
       'Maternal bladder visible', 'Head Measurable', 'Abdomen Measurable',
       'Femur Measurable', 'Transverse plane for Head',
       'Longituidnal plane for Head', 'Oblique or other plane for Head',
       'Transverse plane for Abdomen', 'Longituidnal plane for Abdomen',
       'Oblique or other plane for Abdomen', 'Transverse plane for Femur',
 

In [16]:
# myDf["Femur Visible"] = 0

In [17]:
dfMerged = pd.concat([dfTrain, dfVal], axis=0)
dfMerged = pd.concat([dfMerged, dfTest], axis=0)

In [18]:
dfMerged.head()
print(dfMerged.columns)
# myDf.head()
# print(dfMerged["Amniotic fluid visible"].value_counts())

Index(['img_path', 'uuid', 'study_id', 'fetal_presentation_str', 'ga_boe',
       'ga_expert', 'famli_edd_source', 'famli_edd_source_detail', 'dvp_crf',
       'fetal_presentation', 'ga_absdiff', 'is_anchor', 'tag', 'pidscan',
       'us_plac', 'us_previa', 'placenta_str', 'previa_str', 'Manufacturer',
       'ManufacturerModelName', 'uuid_path_256', 'score', 'pred',
       'pred_cluster', 'File', 'No structures visible', 'Head Visible',
       'Abdomen Visible', 'Chest Visible', 'Femur Visible',
       'Other arm or leg bones visible', 'Umbilical cord visible',
       'Amniotic fluid visible', 'Placenta visible', 'Fetus or CRL visible',
       'Maternal bladder visible', 'Head Measurable', 'Abdomen Measurable',
       'Femur Measurable', 'Transverse plane for Head',
       'Longituidnal plane for Head', 'Oblique or other plane for Head',
       'Transverse plane for Abdomen', 'Longituidnal plane for Abdomen',
       'Oblique or other plane for Abdomen', 'Transverse plane for Femur',
 

In [19]:
columnsToDelete1 = [
       'Chest Visible',
       'Other arm or leg bones visible', 'Umbilical cord visible',
       'Fetus or CRL visible', 'Femur Visible',
       'Maternal bladder visible', 'Head Measurable', 'Abdomen Measurable',
       'Femur Measurable', 'Transverse plane for Head',
       'Longituidnal plane for Head', 'Oblique or other plane for Head',
       'Transverse plane for Abdomen', 'Longituidnal plane for Abdomen',
       'Oblique or other plane for Abdomen', 'Transverse plane for Femur',
       'Longituidnal plane for Femur', 'Oblique or other plane for Femur']

In [20]:
dfMerged = dfMerged.drop(columns=columnsToDelete1)


In [21]:
print(dfMerged.columns)

Index(['img_path', 'uuid', 'study_id', 'fetal_presentation_str', 'ga_boe',
       'ga_expert', 'famli_edd_source', 'famli_edd_source_detail', 'dvp_crf',
       'fetal_presentation', 'ga_absdiff', 'is_anchor', 'tag', 'pidscan',
       'us_plac', 'us_previa', 'placenta_str', 'previa_str', 'Manufacturer',
       'ManufacturerModelName', 'uuid_path_256', 'score', 'pred',
       'pred_cluster', 'File', 'No structures visible', 'Head Visible',
       'Abdomen Visible', 'Amniotic fluid visible', 'Placenta visible'],
      dtype='object')


In [22]:
from skmultilearn.model_selection import iterative_train_test_split

In [23]:
# dfMerged1 = dfMergedFullNoDuplicates.reset_index(inplace=True)



In [24]:
print(dfMerged["Head Visible"].value_counts())
print(dfMerged["Abdomen Visible"].value_counts())
print(dfMerged["Placenta visible"].value_counts())
# print(dfMerged["Femur Visible"].value_counts())
print(dfMerged["No structures visible"].value_counts())
print(dfMerged["Amniotic fluid visible"].value_counts())

Head Visible
0    2508
1     991
Name: count, dtype: int64
Abdomen Visible
0    2949
1     550
Name: count, dtype: int64
Placenta visible
0    2505
1     994
Name: count, dtype: int64
No structures visible
0    2783
1     716
Name: count, dtype: int64
Amniotic fluid visible
1    2407
0    1092
Name: count, dtype: int64


In [28]:
dfMergedX = dfMerged.iloc[:, 0:-5].values
dfMergedY = dfMerged.iloc[:, -5:].values

In [32]:
print(type(dfMergedX))
print(dfMergedY.shape)
print(dfMergedY)

<class 'numpy.ndarray'>
(3499, 5)
[[1 0 0 0 0]
 [0 1 0 1 1]
 [0 1 0 1 0]
 ...
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]]


In [33]:
dfMerged.dtypes



img_path                    object
uuid                        object
study_id                    object
fetal_presentation_str      object
ga_boe                     float64
ga_expert                  float64
famli_edd_source            object
famli_edd_source_detail     object
dvp_crf                    float64
fetal_presentation         float64
ga_absdiff                 float64
is_anchor                    int64
tag                         object
pidscan                     object
us_plac                    float64
us_previa                  float64
placenta_str                object
previa_str                  object
Manufacturer                object
ManufacturerModelName       object
uuid_path_256               object
score                      float64
pred                       float64
pred_cluster                 int64
File                        object
No structures visible        int64
Head Visible                 int64
Abdomen Visible              int64
Amniotic fluid visib

In [34]:
myTrainDfX, myTrainDfY, myTestDfX, myTestDfY = iterative_train_test_split(X=dfMergedX, y=dfMergedY, test_size=0.2)

In [35]:
myTrainDfX, myTrainDfY, myValDfX, myValDfY = iterative_train_test_split(X=myTrainDfX, y=myTrainDfY, test_size=0.2)

In [36]:
print(type(myTrainDfY))

<class 'numpy.ndarray'>


In [37]:
myTrainDf = pd.concat([pd.DataFrame(myTrainDfX, columns=dfMerged.columns[:-5]), pd.DataFrame(myTrainDfY, columns=dfMerged.columns[-5:])], axis=1)
myTestDf = pd.concat([pd.DataFrame(myTestDfX, columns=dfMerged.columns[:-5]), pd.DataFrame(myTestDfY, columns=dfMerged.columns[-5:])], axis=1)
myValDf = pd.concat([pd.DataFrame(myValDfX, columns=dfMerged.columns[:-5]), pd.DataFrame(myValDfY, columns=dfMerged.columns[-5:])], axis=1)

# myTestDf = pd.concat([myTestDfX, myTestDfY], axis=1)
# myValDf = pd.concat([myValDfX, myValDfY], axis=1)

In [38]:
print(myTrainDf.shape)
print(myTestDf.shape)
print(myValDf.shape)

(2239, 30)
(700, 30)
(560, 30)


In [39]:
print(myTrainDf.columns)

Index(['img_path', 'uuid', 'study_id', 'fetal_presentation_str', 'ga_boe',
       'ga_expert', 'famli_edd_source', 'famli_edd_source_detail', 'dvp_crf',
       'fetal_presentation', 'ga_absdiff', 'is_anchor', 'tag', 'pidscan',
       'us_plac', 'us_previa', 'placenta_str', 'previa_str', 'Manufacturer',
       'ManufacturerModelName', 'uuid_path_256', 'score', 'pred',
       'pred_cluster', 'File', 'No structures visible', 'Head Visible',
       'Abdomen Visible', 'Amniotic fluid visible', 'Placenta visible'],
      dtype='object')


In [41]:
print(myTrainDf["Head Visible"].value_counts())
print(myTrainDf["Abdomen Visible"].value_counts())
print(myTrainDf["Placenta visible"].value_counts())
print(myTrainDf["Amniotic fluid visible"].value_counts())
print(myTrainDf["No structures visible"].value_counts())

print(myTestDf["Head Visible"].value_counts())
print(myTestDf["Abdomen Visible"].value_counts())
print(myTestDf["Placenta visible"].value_counts())
print(myTestDf["Amniotic fluid visible"].value_counts())
print(myTestDf["No structures visible"].value_counts())

print(myValDf["Head Visible"].value_counts())
print(myValDf["Abdomen Visible"].value_counts())
print(myValDf["Placenta visible"].value_counts())
print(myValDf["Amniotic fluid visible"].value_counts())
print(myValDf["No structures visible"].value_counts())


Head Visible
0    1605
1     634
Name: count, dtype: int64
Abdomen Visible
0    1887
1     352
Name: count, dtype: int64
Placenta visible
0    1603
1     636
Name: count, dtype: int64
Amniotic fluid visible
1    1541
0     698
Name: count, dtype: int64
No structures visible
0    1781
1     458
Name: count, dtype: int64
Head Visible
0    502
1    198
Name: count, dtype: int64
Abdomen Visible
0    590
1    110
Name: count, dtype: int64
Placenta visible
0    501
1    199
Name: count, dtype: int64
Amniotic fluid visible
1    481
0    219
Name: count, dtype: int64
No structures visible
0    557
1    143
Name: count, dtype: int64
Head Visible
0    401
1    159
Name: count, dtype: int64
Abdomen Visible
0    472
1     88
Name: count, dtype: int64
Placenta visible
0    401
1    159
Name: count, dtype: int64
Amniotic fluid visible
1    385
0    175
Name: count, dtype: int64
No structures visible
0    445
1    115
Name: count, dtype: int64


In [44]:
myTrainDf.to_csv("/mnt/raid/home/ayrisbud/us-famli-pl/src/originalAnnotatedStrtifiedTrain.csv")
myTestDf.to_csv("/mnt/raid/home/ayrisbud/us-famli-pl/src/originalAnnotatedStrtifiedTest.csv")
myValDf.to_csv("/mnt/raid/home/ayrisbud/us-famli-pl/src/originalAnnotatedStrtifiedVal.csv")

In [ ]:
myTrainDf.columns

In [ ]:
# myDf1 = myDf.replace(np.nan, "NO")
# myDf1.head()
myDf.head()

In [ ]:
myDf1 = myDf1.replace("NO", 0)
myDf1 = myDf1.replace("YES", 1)
myDf1.head()


In [ ]:
myDf1.columns
myLabels = ['Head Visible',
       'Abdomen Visible', 'Chest Visible', 'Femur Visible',
       'Other arm or leg bones visible', 'Umbilical cord visible',
       'Amniotic fluid visible', 'Placenta visible', 'Fetus or CRL visible',
       'Maternal bladder visible', 'Head Measurable', 'Abdomen Measurable',
       'Femur Measurable']

In [ ]:
train_df, test_df = train_test_split(myDf1, test_size=0.2)

In [ ]:
train_df, val_df = train_test_split(train_df, test_size=0.2)

In [ ]:
print(train_df.head())

In [ ]:
train_df.to_csv("./annotatedTrain.csv", index=False)
test_df.to_csv("./annotatedTest.csv", index=False)
val_df.to_csv("./annotatedVal.csv", index=False)

In [ ]:
myTrain_df = pd.read_csv("./annotatedTrain.csv")
myTrain_df.head()